---
title: "Statystyka"
author: "Rafał Szyiński, Kajetan Leszak"
date: "`r Sys.Date()`"
output: pdf_document
---

# Statystyka

## Wstęp

```{r libs}
library(ggplot2)
library(readr)
library(dplyr)
```

## Opis baza danych

- Baza pochodzi z eportal
- Baza danych składa się z ...
- Opis poszczególnych kolumn

```{r ladowanie_bazy_danych}
data <- read.csv2("credit_card.xls");
data
```

## Wyliczenie podstawowych statystyk

Statysyka będzie wyliczona z columny items i spent

```{r statystyka_items_i_spent}
frame <- data.frame(
  items_summary=unclass(summary(data$items)),
  spent_summary=unclass(summary(data$spent))
  )
frame
```

## Wykresy

```{r plot_histogram}
ggplot() + 
  geom_bar(
    data=data, 
    aes(x=type_trans, y=items, color=gender, fill=gender), 
    stat="identity"
    ) +
  labs(
    title="Histogram zakupu rodzaju dobra w zależności od płci",
    x="Rodzaj dobra",
    y="Sumaryczna ilość zakupionych produktów"
    ) +
  theme_classic()
```

```{r plot_linear}
# Filtrujemy wysztkie dane pierwszego użytkownika
user_data <- data[data$custid == "8257-BKBEDP-MRF",]

month_numeric <- c("January", "February", "March", "April","May", "June", "July", "August", "September", "October", "November", "December" )

# Zamiana miesiąca z słowa na liczbe np. January=1
month <- match(user_data$month, month_numeric)

user_date_items = data.frame(
  year = user_data$year,
  month = month,
  items = user_data$items
  )

# Sortowanie po roku i miesiącu
sorted_user <- user_date_items[order(user_date_items$year, user_date_items$month),]
# Sumaryczny wektor 
sorted_user$items <- cumsum(sorted_user$items)
data_length = length(sorted_user$items)

ggplot() +
  geom_line(
    data=sorted_user, 
    aes(x = seq(from=1, to=data_length), y = items)) + 
  scale_x_continuous(
    breaks= seq(from=1, to=data_length, by=5), 
    labels=c(paste(rep(2007, 12), month_numeric, sep="-"), paste(rep(2008, 12), month_numeric, sep="-"))) +
  theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))

```





